# source Image
FROM centos:7

# yum upgrade and install global requirements
RUN yum upgrade -y && \
    yum install -y \
      epel-release && \
    yum install -y \
      autoconf \
      bzip2 \
      bzip2-devel \
      libcurl-devel \
      libcrypto-devel \
      openssl-devel \
      R \
      xz-devel \
      zlib-devel

# install global r requirements
RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile
RUN Rscript -e "install.packages('optparse')"
RUN Rscript -e "install.packages('stringr')"
RUN Rscript -e "source('https://bioconductor.org/biocLite.R'); biocLite('Biostrings')"

# install htslib
RUN curl -LO https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 && \
    tar xfj htslib-1.9.tar.bz2 && \
    cd htslib-1.9 && \
    autoheader && \
    autoconf && \
    ./configure && \
    make && \
    make install

# install scramble
COPY . /app
RUN cd /app/cluster_identifier/src && \
    make
RUN ln -s /app/cluster_identifier/src/build/cluster_identifier /usr/local/bin

# define default command
CMD ["Rscript"]
